#server.port=0
#
#spring.datasource.url=jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres?user=postgres.ugboqkryswcahsvshesl&password=RamSharma%4012345
#spring.datasource.username=postgres.ugboqkryswcahsvshesl
#spring.datasource.password=RamSharma@12345
#
#spring.datasource.hikari.maximum-pool-size=10
#spring.datasource.hikari.minimum-idle=2
#spring.datasource.hikari.connection-timeout=30000
#
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=none
#
#spring.data.redis.host=funny-perch-183443.upstash.io
#spring.data.redis.port=6379
#spring.data.redis.password=gQAAAAAAAsyTAAIgcDE2OGNjMGMyNDU4NjM0MjE3OTIwZTU2YTJhN2U0ZTliOQ
#spring.data.redis.ssl.enabled=true
#
#spring.cache.redis.time-to-live=10m
#
#spring.mail.host=localhost
#spring.mail.port=1025
#
#management.server.port=0
#
#jwt.secret=342rfihsafoue234rdfjaioi3y24sdfaio234dflkjop
