spring.application.name=apexbank

server.port=${PORT:8080}

spring.datasource.url=${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REIDS_TOKEN}
spring.data.redis.ssl.enabled=true
spring.cache.redis.time-to-live=10m


spring.mail.host=${EMAIL_HOST:localhost}
spring.mail.port=${EMAIL_PORT:1025}
spring.mail.username=${FROM_EMAIL:test}
spring.mail.password=${EMAIL_APP_PASSWORD:test}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

jwt.secret=${JWT_SECRET}

